/**
 * Admin Domain 전용 스타일 정의
 * 브랜드 컬러: #2a7d55 (초록색 계열)
 */

export const adminColors = {
  primary: "#2a7d55",
  primaryHover: "#216343",
  primaryLight: "#eaf2ed",
  textPrimary: "#1a1a1a",
  textSecondary: "#666666",
  border: "#e0e0e0",
  background: "#f8f9fa",
  white: "#ffffff",
  danger: "#d32f2f",
  dangerLight: "#fdecea",
  success: "#2e7d32",
  successLight: "#edf7ed",
  info: "#0288d1",
  infoLight: "#e1f5fe",
};

export const adminModalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(2px)",
  },
  content: {
    backgroundColor: adminColors.white,
    borderRadius: "12px",
    width: "100%",
    maxWidth: "600px",
    maxHeight: "90vh",
    overflowY: "auto",
    boxShadow: "0 10px 25px rgba(0, 0, 0, 0.1)",
    position: "relative",
    padding: "0",
  },
  header: {
    padding: "20px 24px",
    borderBottom: `1px solid ${adminColors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    backgroundColor: adminColors.white,
    zIndex: 10,
  },
  title: {
    margin: 0,
    fontSize: "1.25rem",
    fontWeight: "600",
    color: adminColors.textPrimary,
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: "1.5rem",
    cursor: "pointer",
    color: adminColors.textSecondary,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    transition: "background-color 0.2s",
  },
  body: {
    padding: "24px",
  },
  footer: {
    padding: "16px 24px",
    borderTop: `1px solid ${adminColors.border}`,
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    backgroundColor: "#fafafa",
  },
  fieldGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  field: {
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "0.875rem",
    fontWeight: "600",
    color: adminColors.textSecondary,
  },
  input: {
    padding: "10px 14px",
    borderRadius: "8px",
    border: `1px solid ${adminColors.border}`,
    fontSize: "0.95rem",
    transition: "all 0.2s",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    padding: "10px 14px",
    borderRadius: "8px",
    border: `1px solid ${adminColors.border}`,
    fontSize: "0.95rem",
    backgroundColor: adminColors.white,
    cursor: "pointer",
    width: "100%",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%23666666' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
    backgroundSize: "16px",
    boxSizing: "border-box",
  }
};
