version: "3.8"

services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: esg-postgis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: esg-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_FLYWAY_REPAIR_ON_MIGRATE: "true"
      SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
      SPRING_FLYWAY_CLEAN_ON_VALIDATION_ERROR: "false"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - upload_data:/home/ubuntu/upload/evidence
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_BACKEND_URL=https://43.200.217.129
        - VITE_WS_URL=wss://43.200.217.129/ws/esg
        - VITE_KAKAO_MAP_KEY=9693dca78bc226b3618605dbc0bce77f
        - VITE_KEA_API_KEY=0158e6e63feeaa94d850ceb2717eb35dd38ef7e913623ad5170645f214bc880e
        - VITE_KOSIS_API_KEY=Y2E5OTlhMTU3NTBhODNjOTY3ZTM5ZmM5Zjk1Y2U4ZjE=
    container_name: nginx-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./nginx/ssl/server.key:/etc/nginx/ssl/server.key:ro
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  upload_data:

networks:
  app-network:
    driver: bridge
