import { useState } from "react";
import { Line } from "react-chartjs-2";
import { useDemoData } from "../../../app/providers/DemoDataProvider";
import PageHeader from "../../../shared/components/PageHeader";
import Card from "../../../shared/components/Card";
import Tabs from "../../../shared/components/Tabs";
import DataTable from "../../../shared/components/DataTable";
const configs={ENVIRONMENT:{label:"환경(E)",cards:[["온실가스 배출량","1,310 tCO₂eq","전년 대비 7.7% 감소"],["전력 사용량","14,330 MWh","목표 대비 96.2%"],["재활용률","82.4%","목표 80% 초과"]]},SOCIAL:{label:"사회(S)",cards:[["임직원","1,250명","전월 대비 12명 증가"],["교육 이수율","97.3%","목표 95% 초과"],["산업재해","1건","개선조치 진행"]]},GOVERNANCE:{label:"거버넌스(G)",cards:[["이사회 참석률","92.5%","목표 90% 초과"],["사외이사 비율","37.5%","전체 8명 중 3명"],["윤리교육","100%","전 임직원 이수"]]}};
export default function PerformancePage(){ const {db}=useDemoData(); const [tab,setTab]=useState("ENVIRONMENT"); const approved=db.metrics.filter(m=>m.status==="APPROVED"&&m.category===tab); const chart={labels:["1월","2월","3월","4월","5월","6월"],datasets:approved.map((m,i)=>({label:m.title,data:m.months,borderColor:["#2a7d55","#3a74b7","#d59231"][i%3],tension:.3}))}; return <div className="page-stack"><PageHeader breadcrumbs={["성과·보고","ESG 실적 조회"]} title="ESG 실적 조회" description="최종 승인된 데이터만 성과 지표와 보고서 집계에 포함됩니다."/><Tabs value={tab} onChange={setTab} items={Object.entries(configs).map(([value,c])=>({value,label:c.label}))}/><div className="performance-cards">{configs[tab].cards.map(([l,v,h])=><article key={l}><span>{l}</span><strong>{v}</strong><small>{h}</small></article>)}</div><Card title="월별 승인 실적 추이"><div className="chart-box">{approved.length?<Line data={chart} options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}}}}/>:<p>승인된 데이터가 없습니다.</p>}</div></Card><Card title="승인 데이터 목록"><DataTable rows={approved} columns={[{key:"indicatorCode",label:"지표코드"},{key:"title",label:"지표명"},{key:"facility",label:"사업장"},{key:"period",label:"기준기간"},{key:"value",label:"승인 실적",render:(v,r)=>`${v.toLocaleString()} ${r.unit}`}]} /></Card></div>; }
